In [2]:
import pandas as pd
import numpy as np
data_root = pd.read_csv("koreanair_stock.csv")

In [3]:
data = data_root[['대비','종가']].replace(',', '', regex=True).astype(int)

In [4]:
dif = []

#1프로 이상 3프로 미만 = 1, 3프로 이상 5프로 미만 = 2, 5프로 이상 3
for i in range(0, len(data)-1):
    if (data.loc[i,"대비"] > 0) & (abs(data.loc[i,"대비"]) >= \
                                 (data.loc[i + 1, "종가"] / 100) * 1) & (abs(data.loc[i,"대비"]) \
                                                                       < (data.loc[i + 1, "종가"] / 100) * 3):
        dif.append(1)
    elif (data.loc[i,"대비"] > 0) & (abs(data.loc[i,"대비"]) >= \
                                   (data.loc[i + 1, "종가"] / 100) * 3) & (abs(data.loc[i,"대비"]) \
                                                                         < (data.loc[i + 1, "종가"] / 100) * 5):
        dif.append(2)
    elif (data.loc[i,"대비"] > 0) & (abs(data.loc[i,"대비"]) >= \
                                   (data.loc[i + 1, "종가"] / 100) * 5):
        dif.append(3)
    elif (data.loc[i,"대비"] < 0) & (abs(data.loc[i,"대비"]) >= \
                                   (data.loc[i + 1, "종가"] / 100) * 1) & (abs(data.loc[i,"대비"])\
                                                                         < (data.loc[i + 1, "종가"] / 100) * 3):
        dif.append(-1)
    elif (data.loc[i,"대비"] < 0) & (abs(data.loc[i,"대비"]) >= \
                                   (data.loc[i + 1, "종가"] / 100) * 3) & (abs(data.loc[i,"대비"])\
                                                                         < (data.loc[i + 1, "종가"] / 100) * 5):
        dif.append(-2)
    elif (data.loc[i,"대비"] < 0) & (abs(data.loc[i,"대비"]) >= \
                                   (data.loc[i + 1, "종가"] / 100) * 5):
        dif.append(-3)
    else :
        dif.append(0)

In [5]:
#마지막 날자 추가
dif.append(0)

In [6]:
len(dif)

187

In [7]:
data_root["증감"] = dif

In [8]:
data_root

,년/월/일,종가,대비,거래량(주),거래대금(원),시가,고가,저가,시가총액(백만),상장주식수(주),증감
0,2020/09/29,"18,850",50,"922,389","17,470,132,150","19,150","19,150","18,800","3,283,853","174,209,713",0
1,2020/09/28,"18,800",450,"966,495","18,103,219,950","18,550","18,900","18,500","3,275,143","174,209,713",1
2,2020/09/25,"18,350",350,"895,129","16,449,493,950","18,100","18,600","18,100","3,196,748","174,209,713",1
3,2020/09/24,"18,000",-550,"1,234,760","22,462,251,500","18,400","18,450","18,000","3,135,775","174,209,713",-1
4,2020/09/23,"18,550",150,"1,071,051","19,859,025,200","18,600","18,850","18,400","3,231,590","174,209,713",0
...,...,...,...,...,...,...,...,...,...,...,...
182,2020/01/08,"26,300",-550,"676,198","17,787,052,350","26,450","26,700","25,950","2,494,414","94,844,634",-1
183,2020/01/07,"26,850",350,"388,103","10,409,787,950","26,500","27,150","26,400","2,546,578","94,844,634",1
184,2020/01/06,"26,500",-800,"690,224","18,261,902,900","26,850","27,100","26,000","2,513,383","94,844,634",-1
185,2020/01/03,"27,300",-550,"572,272","15,794,199,800","28,000","28,150","27,250","2,589,259","94,844,634",-1
186,2020/01/02,"27,850",-650,"303,459","8,503,181,450","28,500","28,550","27,750","2,641,423","94,844,634",0

In [9]:
data_root.to_csv("대비처리.csv", mode = 'w')

In [10]:
data_root["증감"]

0      0
1      1
2      1
3     -1
4      0
      ..
182   -1
183    1
184   -1
185   -1
186    0
Name: 증감, Length: 187, dtype: int64